image: maven:3-openjdk-11

variables:
  MVN_REPO: $CI_PROJECT_DIR/maven-repo

cache:
  paths:
    - $MVN_REPO/

test:
  script:
    - mvn install -B -Dmaven.repo.local=$MVN_REPO

deploy:
  stage: deploy
  script:
    - mvn deploy -B -DskipTests -s ci_settings.xml -Dmaven.repo.local=$MVN_REPO
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - mvn javadoc:javadoc -f gui/pom.xml
  artifacts:
    paths:
      - gui/target/site/apidocs
  publish: gui/target/site/apidocs
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
